---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
exclude_paths:
- bin/
- benchmarks/
- dynamic_struct.gemspec
- Gemfile
- Gemfile.lock
- Guardfile
- Rakefile
- README.md
