---
engines:
  bundler-audit:
    enabled: true
    config:
      path: test/Gemfile.lock
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- bin/
- benchmarks/
- dynamic_struct.gemspec
- Gemfile
- Gemfile.lock
- Guardfile
- Rakefile
- README.md
