---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 100.0
  reek:
    enabled: true

ratings:
  paths:
  - 'lib/**/*.rb'

exclude_paths:
- bin/
- benchmarks/
- spec/
- dynamic_struct.gemspec
- Gemfile
- Gemfile.lock
- Guardfile
- Rakefile
- README.md
